### ISSUE TITLE
Support/guidelines for use with AsyncDisplayKit (Texture)

### ISSUE THREAD

**Issue by dazzz1er** [slackhq/PanModal#14]
### Description

Sorry guys I was looking for a slack that I could drop into to ask this question but I didn't find one. Firstly, thanks for the effort made to open source this - it's great and I think will really fit my use-case.

My question:
Do you have any guidelines or best practices for using AsyncDisplayKit (now Texture) with PanModal? I have heard that ASDK is used internally at Slack and so you have likely used the two together. Specifically I am having problems with `.intrinsicHeight` and also not receiving expected heights in `constrainedSize` when using `.contentHeight(x)` for `longFormHeight` (I suspect I get the full controller height instead of x). I am fairly new to iOS development and brand spanking new to ASDK, so please do say if this is a poor question or if I should direct it elsewhere.

Thanks for any help you can provide!

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

**Comment by tun57** [comment]
Hey @dazzz1er, no worries! Unfortunately, we no longer use ASDK internally so I don't think we've tried to use it with PanModal. 

I've also never used Texture so my knowledge may be limited, but I'd be happy to help debug any issues you may be having, I just need a little more detail to get to the root of the issue.. what values are you getting back for the `constrainedSize` vs what're you expecting?

Note - we adjust the size of the `presentedViewController`'s view so that it's equal to the `.contentHeight` provided (+ bottomSafeAreaInset). Anytime you get changes to the content on the `presentedViewController`, you should call `panModalSetNeedsLayoutUpdate()` so that the positional values can be recalculated/adjusted internally.

**Comment by dazzz1er** [comment]
Hi @tun57 thanks for the quick response... ah right! I'd love to know what you moved to in place of ASDK - AutoLayout, I guess?

Appreciate your offer to help, I was hoping you guys already used ASDK so you could give me some general guidelines I do not expect you to learn ASDK just to help me out!

When I was using `.contentHeight(200)` I was expecting `200` for the height in `constrainedSize` but instead I was getting `747` (when using the simulator for an iPhone XS) - I suspect this is the full view height in the controller. I have found when essentially reproducing the `BasicViewController` from your sample app but returning `true` for `anchorModalToLongForm` I do in fact get the `200` as height in `constrainedSize` as expected (technically `234` as it includes the safe area margins). So that's my main problem solved and I can move forward with that!

Appreciate your help and thanks again for PanModal

**Comment by tun57** [comment]
@dazzz1er we never really used ASDK outside of early stage prototyping but we eventually moved to a custom internal framework built on top of frame based layouts instead of AL (for performance reasons)

Ah I see.. yeah when using `anchorModalToLongForm` we choose to either truncate the `presented view` at the bottom of the screen (in the event of `true`) or return the entire view controller height (capped at `.max` height when `false`) - that's probably why there's a difference in height values

In that case, I'll close out this issue & if you have anything else - feel free to reopen
