### ISSUE TITLE
Pan Modal does not respect definesPresentationContext

### ISSUE THREAD

**Issue by cdstamper** [slackhq/PanModal#40]
### Description

Pan Modal does not respect definesPresentationContext. Presented PanModals always appear at the TOP of the navigation hierarchy, even if a lower container has `definesPresentationContext=true`.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [X] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

PanModal presenter should find the lowest container with `definesPresentationContext=true` rather than always finding the topmost container, as expected in UIKit and documented: https://developer.apple.com/documentation/uikit/uiviewcontroller/1621456-definespresentationcontext

This is probably because the presentation style is currently set to custom, and this UIKit behavior is only provided when ModalPresentationStyle is currentContext or overCurrentContext. Semantically I feel Pan Modal best models an overCurrentContext presentation style.

#### Reproducible in:

PanModal version: 1.2.4

iOS version: iOS 12.4

#### Steps to reproduce:

1. Create a top-level container (eg UITabBarController)
2. Create a lower-level container (eg UINavigationController) with `definesPresentationContext=true`: this container _should_ present the modal.
3. Create a content view controller inside of the lower-level nav controller.
4. Present a Pan Modal from the content view controller.

#### Expected result:
Pan Modal is presented on the Navigation Controller, allowing any full screen presentation coming from a top-level Tab Bar to appear overtop the pan modal.

#### Actual result:
Pan Modal is presented on the topmost Tab Bar Controller, _preventing_ any full screen presentation from covering it.

#### Attachments:

> Warning: Attempt to present <SomeModal: xx>  on <TopmostRoot: xx> which is already presenting <PanModal: xx>
😢

**Comment by danqing** [comment]
+1 on overCurrentContext. I'm trying to do a modal that looks like what's in Apple Maps - a UIVisualEffectsView that has the presenting VC blurred underneath. This isn't possible with the current set up.

**Comment by ste57** [comment]
Hi @cdstamper 

Apologies for the delayed response & thanks for reporting. Unfortunately, I don't think the issue around `definesPresentationContext` being respected across child view controllers is specific to this library. From what I understand, this is a bug within the iOS presentation API - when using `.custom` as the presentationStyle - we don't automatically get the first VC in the hierarchy that has definesPresentationContext set to true. Specific to PanModal, since we rely pretty heavily on a custom `presentationController`, it would be pretty difficult to support an `overCurrentContext` type style without having to directly manipulate the `presentingViewController`'s own view hierarchy - which can lead to unexpected results.

Let me know if this answers your question.
Stephen

**Comment by osdnk** [comment]
You're always welcome to do reparenting  ¯\_(ツ)_/¯ 
I made it workable with some workaround in my lib (bindings for PanModal for RN)
https://github.com/osdnk/react-native-slack-bottom-sheet/blob/master/ios/UIViewController%2BPanModalPresenter.swift#L25

**Comment by f0rr0** [comment]
Hey, @osdnk can you please explain what you did in your lib to make this work?
